export const MANAGER_LIST_REQUEST = 'MANAGER_LIST_REQUEST'
export const MANAGER_LIST_SUCCESS = 'MANAGER_LIST_SUCCESS'
export const MANAGER_LIST_FAIL = 'MANAGER_LIST_FAIL'

export const DETAIL_MANAGER_REQUEST = 'DETAIL_MANAGER_REQUEST'
export const DETAIL_MANAGER_SUCCESS = 'DETAIL_MANAGER_SUCCESS'
export const DETAIL_MANAGER_FAIL = 'DETAIL_MANAGER_FAIL'

export const DELETE_MANAGER_REQUEST = 'DELETE_MANAGER_REQUEST'
export const DELETE_MANAGER_SUCCESS = 'DELETE_MANAGER_SUCCESS'
export const DELETE_MANAGER_FAIL = 'DELETE_MANAGER_FAIL'

export const CREATE_MANAGER_REQUEST = 'CREATE_MANAGER_REQUEST'
export const CREATE_MANAGER_SUCCESS = 'CREATE_MANAGER_SUCCESS'
export const CREATE_MANAGER_FAIL = 'CREATE_MANAGER_FAIL'

export const UPDATE_MANAGER_REQUEST = 'UPDATE_MANAGER_REQUEST'
export const UPDATE_MANAGER_SUCCESS = 'UPDATE_MANAGER_SUCCESS'
export const UPDATE_MANAGER_FAIL = 'UPDATE_MANAGER_FAIL'

export const SEARCH_MANAGER_REQUEST = 'SEARCH_MANAGER_REQUEST'
export const SEARCH_MANAGER_SUCCESS = 'SEARCH_MANAGER_SUCCESS'
export const SEARCH_MANAGER_FAIL = 'SEARCH_MANAGER_FAIL'